language: node_js
node_js: '0.10'
sudo: false
cache:
  - apt
  - directories:
    - node_modules
addons:
  apt:
    packages:
# Depends on https://github.com/travis-ci/travis-ci/issues/4041
#     - icoutils
    - icnsutils
    - librsvg2-bin
    - wine

script:
# See above for dependency
# - make
- make travis
