language: node_js
node_js: '0.10'
sudo: false
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
    - librsvg2-bin
# Depends on https://github.com/travis-ci/travis-ci/issues/3884
#     - icnsutils

script:
- node_modules/.bin/coffeelint src
# See above for dependency
# - make
