language: node_js
node_js: "6"
sudo: required
os:
- linux
- osx
dist: trusty
osx_image: xcode8.2
services:
- docker
addons:
  apt:
    packages:
    - libavahi-compat-libdnssd-dev

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $TRAVIS_BUILD_DIR/.electron

before_install:
- if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew install icoutils libicns librsvg; fi

before_script:
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then node ci/cache-prebuilt-electron.js; fi

script: ci/script.sh
