language: node_js
node_js: '0.12'
sudo: false
cache:
- apt
- directories:
  - node_modules
  - $HOME/.electron
addons:
  apt:
    packages:
    - icoutils
    - icnsutils
    - nsis
    - wine

script:
- make
