language: node_js
node_js: "6"
sudo: required
os:
- linux
- osx
dist: trusty
osx_image: xcode8.2
services:
- docker

cache:
  directories:
  - node_modules
  - $HOME/.electron

before_install:
- if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew install icoutils librsvg makeicns; fi

script: ci/script.sh
