language: node_js
node_js: '0.12'
sudo: false
cache:
- apt
- directories:
  - node_modules
  - $HOME/.electron
addons:
  apt:
    packages:
    - icoutils
    - icnsutils
    - nsis
    - wine
    # Blocked by https://github.com/travis-ci/apt-package-whitelist/issues/588
    # - genisoimage
env:
  global:
  - DMG=/tmp/libdmg-hfsplus/build/dmg/dmg
  - GENISOIMAGE=/tmp/genisoimage/usr/bin/genisoimage

before_install: ci/before_install.sh

script:
- make
