language: node_js
node_js: "5"
sudo: false
cache:
- apt
- bundler
- directories:
  - node_modules
  - $HOME/.electron
addons:
  apt:
    packages:
    # Blocked by https://github.com/travis-ci/apt-package-whitelist/issues/588
    # Handled in ci/before_install.sh + env.global in the meantime
    # - genisoimage
    - icoutils
    - icnsutils
    - rpm
    - nsis
    - wine
env:
  global:
  - DMG=/tmp/libdmg-hfsplus/build/dmg/dmg
  - GENISOIMAGE=/tmp/genisoimage/usr/bin/genisoimage

before_install: ci/before_install.sh

script:
- make
