language: node_js
node_js: '0.10'
sudo: false
cache:
  - apt
  - directories:
    - node_modules
addons:
  apt:
    packages:
    - icoutils
    - icnsutils
    - librsvg2-bin
    - wine

script:
- make
